### ISSUE TITLE
Add option 'public' to cache providers

### ISSUE THREAD

**Issue by IndraGunawan** [doctrine/DoctrineCacheBundle#101]
in case cache provider only use on other services argument, so i dont need that provider set as public service.

for example i use doctrine cache for caching the validation metadata

``` yml
# service.yml
services:
    app.cache.validation:
        class: "Symfony\\Component\\Validator\\Mapping\\Cache\\DoctrineCache"
        arguments: ["@doctrine_cache.providers.validation_cache"]
        public: false

# config.yml
doctrine_cache:
    providers:
        validation_cache:
            namespace: "validation_cache:"
            redis:
                host: "..."
                port: "..."
                database: "..."

framework:
    validation:
        cache: app.cache.validation
```

the service `doctrine_cache.providers.validation_cache` just as other service arguments.

so i think it would be great if it can set as 'public' option

``` yml
# config.yml
doctrine_cache:
    providers:
        validation_cache:
            namespace: "validation_cache:"
            redis:
                host: "..."
                port: "..."
                database: "..."
            public: false
```
