### ISSUE TITLE
[RFC] Advanced cache wrapper

### ISSUE THREAD

**Issue by EmanueleMinotto** [doctrine/DoctrineCacheBundle#26]
Hi all, could be interesting for this bundle to include (optionally) the [CEikermann/advcache](https://github.com/CEikermann/advcache).

Configuration example:

``` yml
doctrine_cache:
  providers:
    test:
      type: apc
      advanced: true
```

I'm looking for feedbacks before starting a PR.
Thanks
