### ISSUE TITLE
Provider alias

### ISSUE THREAD

**Issue by FabioBatSilva** [doctrine/DoctrineCacheBundle#3]
Add support for provider alias

Example configuration :

```
doctrine_cache:
    alias:
       my_apc_cache_alias_foo: my_apc_cache
       my_apc_cache_alias_bar: my_apc_cache

    providers:
        my_apc_cache:
            type: apc
            namespace: my_apc_ns
```
