### ISSUE TITLE
Can not define Redis database in config.yml for cache drivers

### ISSUE THREAD

**Issue by machinez** [doctrine/DoctrineCacheBundle#46]
We have a production Redis cache and would like to specify a database other than the default 0 (0-15 selectable in Redis). Specifying a database in config.yml causes InvalidConfigurationException in ArrayNode.php line 309.

![doctrinecachebundle](https://cloud.githubusercontent.com/assets/819865/6257519/b38d3580-b78e-11e4-9f88-57ef5d483237.png)

```yaml
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
        types:

    orm:
        metadata_cache_driver: 
            type: redis
            database: 8
            host: 192.168.0.1
        query_cache_driver:
            type: redis
            database: 8
            host: 192.168.0.1
        result_cache_driver:
            type: redis
            database: 8
            host: 192.168.0.1
```
