### ISSUE TITLE
Providers that relies on external configuration should also accept services

### ISSUE THREAD

**Issue by guilhermeblanco** [doctrine/DoctrineCacheBundle#5]
According to some configuration seen on RiakDefinition, it is possible to mix and match services as constructor arguments of cache providers.
The perfect example of this is the situation we face at @instaclick where we take advantage of ICBaseRiakBundle to create services for Connection and Bucket and we may want to create cache providers around them.
By taking this into consideration, I'd assume we could also write configuration like:

``` yaml
doctrine_cache:
    providers:
        default_result_cache:
            riak:
                namespace: 'foo'
                bucket:
                    id: 'ic_base_riak.bucket.result_cache'
```
