### ISSUE TITLE
Unrecognized options "directory, extension" when using "type: file_system"

### ISSUE THREAD

**Issue by zeromodule** [doctrine/DoctrineCacheBundle#55]
I am trying to setup DoctrineCacheBundle.

**Here is config:**

<pre>
doctrine_cache:
    providers:
        my_file_cache:
            type: file_system
            directory: "%kernel.root_dir%/cache"
            extension: cache
</pre>

**And result is:**

`InvalidConfigurationException in ArrayNode.php line 309:
Unrecognized options "directory, extension" under "doctrine_cache.providers.my_file_cache"`

**Comment by kpotemichev** [comment]
it duplicates https://github.com/doctrine/DoctrineCacheBundle/issues/38

**Comment by stof** [comment]
@kpotemichev no it does not. #38 was about configuration in the DoctrineBundle config.

the proper config looks like that:

```yaml
doctrine_cache:
    providers:
        my_file_cache:
            type: file_system
            file_system:
                directory: "%kernel.root_dir%/cache"
                extension: cache
```

and the ``type`` can actually be omitted here. It will be guessed based on the key being filled.
