### ISSUE TITLE
How to configure Redis provider?

### ISSUE THREAD

**Issue by silasrm** [doctrine/DoctrineCacheBundle#64]
Hi,

I'm try this config:
```
doctrine_cache:
    providers:
        redis_cache:
            redis:
                host: localhost
                port: 6379
```

And I'm using calling ```$cache = $this->container->get('doctrine_cache.providers.redis_cache');```.

In development is OK, but in production throw error:
Fatal error: Class 'Redis' not found in (...)/app/cache/prod/appProdProjectContainer.php on line 693.

Where is the mistake?

Thank's!
