### ISSUE TITLE
Illegal offset type in isset or empty - double call to $this->get()

### ISSUE THREAD

**Issue by AlexC** [doctrine/DoctrineCacheBundle#68]
I'm trying to configure DoctrineCacheBundle with MongoDB, however whenever I get the service from Symfony DI it results in the following PHP Warning:

**Warning: Illegal offset type in isset or empty**

Here is my config:

```yml
# Doctrine cache
doctrine_cache:
    providers:
        cake:
            type: mongodb
            namespace: cake
            mongodb:
                server: "%mongodb_server%"
                database_name: "dbname"
                collection_name: "cache"
```

And in my Controller:

```php
$this->get('doctrine_cache.providers.cake')
```

After some debugging I have tracked it down to the file **app/cache/dev/appDevDebugProjectContainer.php** which contains the following code:

```php
    protected function getDoctrineCache_Providers_CakeService()
    {
        $this->services['doctrine_cache.providers.cake'] = $instance = new \Doctrine\Common\Cache\MongoDBCache($this->get($this->get('doctrine_cache.services.cake.connection'))->selectCollection('dbname', 'cache'));

        $instance->setNamespace('cake');

        return $instance;
    }
```

The issue is the double `$this->get($this->get())` as it's trying to pass an instance of ``MongoClient`` to the outer `$this->get()` call.

From what I can see the configuration is correct and it appears to be a bug within the following file  which ultimately generates the above ``getDoctrineCache_Providers_CackeService`` method, however I can't work out what's causing it.

https://github.com/doctrine/DoctrineCacheBundle/blob/master/DependencyInjection/Definition/MongodbDefinition.php#L43

Removing the 2nd call to ``$this->get()`` resolves the issue and everything works as it should.

Thoughts?
