### ISSUE TITLE
contains always return TRUE - Provider Memcache 2.2.7

### ISSUE THREAD

**Issue by radli** [doctrine/DoctrineCacheBundle#70]
OS: windows 7
PHP Version 5.5.10
memcache Version	2.2.7

```php
/* @var $cache \Doctrine\Common\Cache\CacheProvider */
$cache = $this->get('pro_cache');
$cache_id = 'user_data:'.$userId;
var_dump($cache->contains($cache_id)); // Return Always true
$cache->save($cache_id, 1, 300);
```

**Comment by radli** [comment]
config.yml:
```yml
doctrine_cache:
    aliases:
        pro_cache: pro_memcache
        
    providers:
        pro_memcached:
            memcached:
               servers: 
                  127.0.0.1: 11211
        pro_memcache:
            memcache:
               servers: 
                  127.0.0.1: 11211
```
