### ISSUE TITLE
Can not define Predis scheme config.yml for cache drivers

### ISSUE THREAD

**Issue by Avtonom** [doctrine/DoctrineCacheBundle#88]
[Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined index: scheme in /vendor/doctrine/doctrine-cache-bundle/DependencyInjection/Definition/PredisDefinition.php line 49

possibly after 8290005dd8366484e61a47b62ee75f4fe18abede

\app\config\config.yml
```
    orm:
        entity_managers:
            default:
                second_level_cache:
                    region_cache_driver:
                        type: predis
                    enabled: true
```

**Comment by Avtonom** [comment]
merge? https://github.com/phoenixgao/DoctrineCacheBundle/commit/2d6f157740877f731d263de8e52a8295423b7c01

**Comment by stof** [comment]
@guilhermeblanco the fact that the definition classes are used also in other doctrine bundle indeed means that they have to check the config they receive (as the configuration is not yet taken from DoctrineCacheBundle in other bundles)

**Comment by Avtonom** [comment]
@stof then please tell me if I can not set the parameter "scheme " and it is not taken from the configuration, it turns out this bundle does not work?

**Comment by Avtonom** [comment]
problem in: /vendor/doctrine/doctrine-cache-bundle/Doctrine/Bundle/DoctrineCacheBundle/DependencyInjection/SymfonyBridgeAdapter.php:94

**Comment by Avtonom** [comment]
doctrine:
    orm:
        entity_managers:
            default:
                query_cache_driver:
                    type: predis
                    cache_provider: predis
                metadata_cache_driver:
                    type: predis
                    cache_provider: predis
                result_cache_driver:
                    type: predis
                    cache_provider: predis

doctrine_cache:
    providers:
        predis:
            type: predis

**Comment by keltanas** [comment]
But, I'm too trying use Doctrine Cache Bundle corresponds [documentation](https://symfony.com/doc/current/bundles/DoctrineCacheBundle/reference.html#predis), and my config dont work, when I'm adding `host` options.

```
doctrine_cache:
    providers:
        predis:
            type: predis
            host: 192.168.1.1
```

```
InvalidConfigurationException in ArrayNode.php line 317:
Unrecognized option "host" under "doctrine_cache.providers.predis"
```

How do it should work? And why need to use Snc Redis Bundle?
Thank you for answer.

**Comment by kaiwa** [comment]
Same here, it is not possible to define any provider settings for predis.

And in that config posted above doctrine cache is _not_ using the client configured under snc_redis, just change `dsn: redis://localhost` to `dsn: redis://thissucks` and you'll see it's still using localhost.

**Comment by mikeSimonson** [comment]
Can someone write a failing unit test ?

**Comment by kaiwa** [comment]
> Unrecognized option "host" under "doctrine_cache.providers.predis"

Umm it's because the options must be specified in another child node:

```
        predis:
            type: predis
                                  <-- not there
            predis:
                host: '....'      <-- but here
```

I think the documentation is missing a complete example for that.
