### ISSUE TITLE
I can't configure DoctrineCacheBundle to work with Redis

### ISSUE THREAD

**Issue by yura3d** [doctrine/DoctrineCacheBundle#91]
Hello!
I'm trying to configure DoctrineCacheBundle to work with Redis.
I've installed DoctrineCacheBundle according to [Installation page](https://symfony.com/doc/current/bundles/DoctrineCacheBundle/installation.html#step-1-download-the-bundle), then I've changed my config file **config.yml**:

```
doctrine:
    ...
    orm:
        ...
        metadata_cache_driver:
            type: redis
            host: 127.0.0.1
        query_cache_driver:
            type: redis
            host: 127.0.0.1
        result_cache_driver:
            type: redis
            host: 127.0.0.1
```

Now, through redis-cli, I can see some new keys in Redis, that are generated by DoctrineCacheBundle. For example:
- DoctrineNamespaceCacheKey[sf2orm_default_cc97f00cfbaec05a97bfe2b8e97e19bbb86c6b60493b43afbb6b4f0e5a54055c]
- sf2orm_default_cc97f00cfbaec05a97bfe2b8e97e19bbb86c6b60493b43afbb6b4f0e5a54055c[AppBundle\Entity\Location$CLASSMETADATA][1]

But when I'm trying to execute _GET_ Redis command to get value for any of these keys, I see _nil_. When I turn redis-cli to _monitor_ mode, I can see that DoctrineCacheBundle (while people are browsing my site) tries to execute _SET_ Redis command to save some binary data (it looks like \x09c\x08b etc) to these keys. But _GET_ for all these keys is always _nil_. Accordingly, I see through profiler, that cache is not working and all the requests come to MySQL server directly.

DoctrineCacheBundle 1.3
Symfony 3.0.3
PHP 7.0.4 with phpredis and igbinary extensions
Redis 3.0.7
